services:
  app:
    build: .
    container_name: go_graphql_api
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
