package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"

	"github.com/LamichhaneBibek/graphql-go/graph/model"
)

// CreatePost is the resolver for the createPost field.
func (r *mutationResolver) CreatePost(ctx context.Context, input model.CreatePostInput) (*model.Post, error) {
	userID, err := requireAuth(ctx)
	if err != nil {
		return nil, err
	}
	post, err := r.PostService.Create(userID, input.Title, input.Content)
	if err != nil {
		return nil, err
	}
	return mapPost(post), nil
}

// UpdatePost is the resolver for the updatePost field.
func (r *mutationResolver) UpdatePost(ctx context.Context, id string, input model.UpdatePostInput) (*model.Post, error) {
	userID, err := requireAuth(ctx)
	if err != nil {
		return nil, err
	}
	pid, err := parseID(id)
	if err != nil {
		return nil, err
	}
	post, err := r.PostService.Update(pid, userID, input.Title, input.Content)
	if err != nil {
		return nil, err
	}
	return mapPost(post), nil
}

// DeletePost is the resolver for the deletePost field.
func (r *mutationResolver) DeletePost(ctx context.Context, id string) (bool, error) {
	userID, err := requireAuth(ctx)
	if err != nil {
		return false, err
	}
	pid, err := parseID(id)
	if err != nil {
		return false, err
	}
	if err := r.PostService.Delete(pid, userID); err != nil {
		return false, err
	}
	return true, nil
}

// PublishPost is the resolver for the publishPost field.
func (r *mutationResolver) PublishPost(ctx context.Context, id string) (*model.Post, error) {
	callerID, err := requireAuth(ctx)
	if err != nil {
		return nil, err
	}
	if err := r.requireRole(ctx, callerID, "admin"); err != nil {
		return nil, err
	}
	pid, err := parseID(id)
	if err != nil {
		return nil, err
	}
	post, err := r.PostService.Publish(pid)
	if err != nil {
		return nil, err
	}
	return mapPost(post), nil
}

// Posts is the resolver for the posts field.
func (r *queryResolver) Posts(ctx context.Context) ([]*model.Post, error) {
	posts, err := r.PostService.GetAll()
	if err != nil {
		return nil, err
	}
	result := make([]*model.Post, len(posts))
	for i, p := range posts {
		result[i] = mapPost(&p)
	}
	return result, nil
}

// Post is the resolver for the post field.
func (r *queryResolver) Post(ctx context.Context, id string) (*model.Post, error) {
	pid, err := parseID(id)
	if err != nil {
		return nil, err
	}
	post, err := r.PostService.GetByID(pid)
	if err != nil {
		return nil, err
	}
	return mapPost(post), nil
}
