package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"

	"github.com/LamichhaneBibek/graphql-go/graph/model"
)

// Register is the resolver for the register field.
func (r *mutationResolver) Register(ctx context.Context, input model.RegisterInput) (*model.AuthResponse, error) {
	result, err := r.AuthService.Register(input.Name, input.Email, input.Password)
	if err != nil {
		return nil, err
	}
	return &model.AuthResponse{Token: result.Token, User: mapUser(result.User)}, nil
}

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, input model.LoginInput) (*model.AuthResponse, error) {
	result, err := r.AuthService.Login(input.Email, input.Password)
	if err != nil {
		return nil, err
	}
	return &model.AuthResponse{Token: result.Token, User: mapUser(result.User)}, nil
}

// UpdateUserRole is the resolver for the updateUserRole field.
func (r *mutationResolver) UpdateUserRole(ctx context.Context, userID string, roleID string) (*model.User, error) {
	callerID, err := requireAuth(ctx)
	if err != nil {
		return nil, err
	}
	if err := r.requireRole(ctx, callerID, "admin"); err != nil {
		return nil, err
	}
	uid, err := parseID(userID)
	if err != nil {
		return nil, err
	}
	rid, err := parseID(roleID)
	if err != nil {
		return nil, err
	}
	user, err := r.UserService.UpdateRole(uid, rid)
	if err != nil {
		return nil, err
	}
	return mapUser(user), nil
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context) ([]*model.User, error) {
	if _, err := requireAuth(ctx); err != nil {
		return nil, err
	}
	users, err := r.UserService.GetAll()
	if err != nil {
		return nil, err
	}
	result := make([]*model.User, len(users))
	for i, u := range users {
		result[i] = mapUser(&u)
	}
	return result, nil
}

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context, id string) (*model.User, error) {
	if _, err := requireAuth(ctx); err != nil {
		return nil, err
	}
	uid, err := parseID(id)
	if err != nil {
		return nil, err
	}
	user, err := r.UserService.GetByID(uid)
	if err != nil {
		return nil, err
	}
	return mapUser(user), nil
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*model.User, error) {
	userID, err := requireAuth(ctx)
	if err != nil {
		return nil, err
	}
	user, err := r.UserService.GetByID(userID)
	if err != nil {
		return nil, err
	}
	return mapUser(user), nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
